/* ============================================================
   Native lesson slides: the visual design for lessons rebuilt from their
   Canva decks (each deck page is one slide, with the deck's exact wording).
   Slide HTML is generated by build/slides/make_lesson.py into
   build/lessons/lessonNN.js; these are its components:
     .cs-label   the deck's section label (e.g. CLAIM FILING)
     .cs-lead    the page's main statement
     .cs-grid / .cs-card   icon cards (.cs-card.dark, .cs-card.soft)
     .cs-flow    numbered steps with connectors
     .cs-list    a list with icons (check, dot, step numbers)
     .cs-do / .cs-dont     ✅ correct / ❌ do not boxes
     .cs-tip, .cs-warn     callouts
     .cs-table   a table
     .cs-fig     a document image: click to see it full size
     .cs-hero    title and closing slides (.photo: over the deck's photo)
     .cs-media   the points beside the deck page's photo; .cs-card.num a numbered point
     .cs-pages   a deck page shown as its own image (build/slides/image_lesson.py)
     .cs-cover   a correspondence slide: the title on the deck's photo beside the document (orange frame)
   In full screen and the slides window a page fills the screen: no width cap, no presenter
   column, and the text scales with the screen.
   Loaded after js/ft-updates.js.
   ============================================================ */
(function(){
const css = `
.cs{display:flex;flex-direction:column;gap:14px;font-size:15.5px;line-height:1.55;color:var(--ink);}
/* the slide stage styles lesson text bold and centered: these slides set their own */
.ft-body .cs p, .ft-body .cs li, .ft-body .cs td{font-weight:400 !important;text-align:left !important;}
.ft-body .cs .cs-lead{font-weight:500 !important;}
.ft-body .cs b{font-weight:700;}
.ft-body .cs ul{text-align:left;}
.ft-body .cs .cs-flow li{text-align:center !important;font-weight:700 !important;}
.ft-body .cs .cs-flow li span{font-weight:500;}
.ft-body .cs .cs-hero p{color:rgba(255,255,255,.88);}
.ft-body .cs{font-weight:400;} .ft-body .cs p{margin:0 !important;}
.ft-body .cs .cs-list li, .ft-body .cs .cs-flow li{margin:0 !important;list-style:none;}
.ft-body .cs .cs-list li{padding:8px 12px 8px 40px !important;}
.ft-body .cs .cs-list li::before, .ft-body .cs .cs-flow li::before{position:absolute !important;display:flex !important;margin:0 !important;vertical-align:baseline !important;}
.ft-body .cs .cs-list li::before{left:10px !important;top:8px !important;width:20px !important;height:20px !important;}
.ft-body .cs .cs-list.dot li::before{left:17px !important;top:15px !important;width:8px !important;height:8px !important;}
.ft-body .cs .cs-flow li::before{top:10px !important;left:50% !important;width:24px !important;height:24px !important;}
/* a tall slide scrolls inside the card instead of being cut off */
.lesson-card.ft-section:has(.cs){overflow-y:auto;}
.cs-label{align-self:flex-start;display:inline-flex;align-items:center;gap:6px;font-size:11.5px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:var(--orange-deep);background:#FBF1E6;border:1px solid #F0D2AE;border-radius:999px;padding:4px 12px;}
.cs-lead{font-size:16.5px;line-height:1.6;color:var(--ink);margin:0;max-width:78ch;}
.cs-lead b, .cs p b{color:var(--navy);}
.cs-sub{font-size:12.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--navy);margin:4px 0 -4px;}
.cs p{margin:0;}
.cs-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:12px;}
.cs-grid.c2{grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));}
.cs-grid.c3{grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));}
.cs-card{position:relative;background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px 14px;box-shadow:0 1px 2px rgba(22,24,41,.04),0 10px 24px -18px rgba(22,24,41,.35);display:flex;flex-direction:column;gap:6px;min-width:0;}
.cs-card .cs-ic{width:34px;height:34px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:20px;background:#FBF1E6;flex-shrink:0;}
.cs-card b{font-size:15px;color:var(--navy);line-height:1.35;}
.cs-card p, .cs-card li{font-size:14px;color:var(--ink-soft);line-height:1.5;}
.cs-card ul{margin:2px 0 0;padding-left:18px;} .cs-card li{margin:2px 0;}
.cs-card.dark{background:linear-gradient(145deg,var(--navy),var(--navy-soft));border-color:transparent;color:#fff;}
.cs-card.dark b{color:#F0C08A;} .cs-card.dark p, .cs-card.dark li{color:rgba(255,255,255,.86);}
.cs-card.dark .cs-ic{background:rgba(240,192,138,.16);}
.cs-card.soft{background:#F6F7FB;box-shadow:none;}
.cs-card.accent{border-top:4px solid var(--orange);}
.cs-card .cs-tag{align-self:flex-start;font-size:11px;font-weight:800;letter-spacing:.06em;border-radius:999px;padding:2px 9px;background:var(--navy);color:#fff;}
.cs-card .cs-tag.o{background:var(--orange);}
.cs-flow{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,150px),1fr));gap:10px;counter-reset:cs;}
.cs-flow li{counter-increment:cs;position:relative;background:#fff;border:1px solid var(--line);border-radius:14px;padding:38px 12px 12px;font-size:14px;font-weight:700;color:var(--navy);text-align:center;line-height:1.35;}
.cs-flow li::before{content:counter(cs);position:absolute;top:10px;left:50%;transform:translateX(-50%);width:24px;height:24px;border-radius:50%;background:var(--orange);color:#fff;font-size:12.5px;font-weight:800;display:flex;align-items:center;justify-content:center;}
.cs-flow li:not(:last-child)::after{content:"→";position:absolute;right:-10px;top:50%;transform:translateY(-50%);width:18px;height:18px;border-radius:50%;background:var(--navy);color:#fff;font-size:11px;display:flex;align-items:center;justify-content:center;z-index:1;}
.cs-flow li span{display:block;font-size:12.5px;font-weight:500;color:var(--ink-soft);margin-top:4px;}
.cs-list{list-style:none;margin:0;padding:0;display:grid;gap:8px;}
.cs-list li{position:relative;padding:8px 12px 8px 40px;background:#fff;border:1px solid var(--line);border-radius:12px;font-size:14.5px;line-height:1.5;}
.cs-list li::before{content:"✓";position:absolute;left:10px;top:8px;width:20px;height:20px;border-radius:50%;background:var(--success-bg);color:var(--success);font-size:12px;font-weight:800;display:flex;align-items:center;justify-content:center;}
.cs-list.dot li::before{content:"";width:8px;height:8px;left:17px;top:15px;background:var(--orange);}
.cs-list.num{counter-reset:csl;} .cs-list.num li{counter-increment:csl;}
.cs-list.num li::before{content:counter(csl);background:var(--navy);color:#fff;}
.cs-list.two{grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));}
.cs-list li b{color:var(--navy);}
.cs-split{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:14px;align-items:start;}
.cs-do, .cs-dont{border-radius:14px;padding:12px 16px;}
.cs-do{background:var(--success-bg);border:1px solid #BFD9C8;} .cs-dont{background:var(--danger-bg);border:1px solid #E7C3BD;}
.cs-do > b, .cs-dont > b{display:block;font-size:13px;font-weight:800;letter-spacing:.04em;margin-bottom:6px;}
.cs-do > b{color:var(--success);} .cs-dont > b{color:var(--danger);}
.cs-do ul, .cs-dont ul{margin:0;padding-left:18px;} .cs-do li, .cs-dont li{margin:3px 0;font-size:14.5px;}
.cs-code{font-family:'JetBrains Mono',ui-monospace,monospace;font-size:13.5px;background:#fff;border:1px dashed var(--line);border-radius:8px;padding:2px 8px;}
.cs-tip, .cs-warn, .cs-note{display:flex;gap:10px;align-items:flex-start;border-radius:14px;padding:12px 16px;font-size:14.5px;line-height:1.5;}
.cs-tip{background:#FBF1E6;border-left:4px solid var(--orange);}
.cs-warn{background:var(--danger-bg);border-left:4px solid var(--danger);}
.cs-note{background:#EEF1F8;border-left:4px solid var(--navy);}
.cs-tip::before{content:"💡";} .cs-warn::before{content:"⚠️";} .cs-note::before{content:"📌";}
.cs-table{width:100%;border-collapse:separate;border-spacing:0;font-size:13.5px;border:1px solid var(--line);border-radius:14px;overflow:hidden;background:#fff;}
.cs-table th{background:var(--navy);color:#fff;text-align:left;font-weight:700;padding:9px 12px;font-size:12.5px;letter-spacing:.02em;}
.cs-table td{padding:8px 12px;border-top:1px solid var(--line);vertical-align:top;}
.cs-table tr:nth-child(even) td{background:#F8F9FC;}
.cs-table td:first-child{font-weight:700;color:var(--navy);}
.cs-tablewrap{overflow-x:auto;border-radius:14px;}
.cs-fig{margin:0;display:flex;flex-direction:column;align-items:center;gap:6px;}
.cs-figs{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:14px;align-items:start;}
.cs-fig img{max-width:100%;max-height:52vh;border-radius:10px;border:1px solid var(--line);box-shadow:0 12px 28px -18px rgba(22,24,41,.5);cursor:zoom-in;background:#fff;}
.cs-fig figcaption{font-size:12.5px;color:var(--ink-soft);font-weight:600;}
.cs-hero{min-height:44vh;display:flex;flex-direction:column;justify-content:center;gap:12px;padding:28px 30px;border-radius:18px;background:radial-gradient(circle at 85% 20%,rgba(219,132,55,.35),transparent 45%),linear-gradient(140deg,var(--navy-deep),var(--navy));color:#fff;}
.cs-hero .cs-label{background:rgba(240,192,138,.14);border-color:rgba(240,192,138,.4);color:#F0C08A;}
.cs-hero .cs-big{font-family:'Fraunces',Georgia,serif;font-size:clamp(28px,4vw,44px);font-weight:700;line-height:1.15;color:#fff;}
.cs-hero p{font-size:17px;color:rgba(255,255,255,.88);max-width:62ch;}
.cs-stat{display:flex;flex-wrap:wrap;gap:10px;}
.cs-stat span{background:var(--navy);color:#fff;border-radius:12px;padding:10px 14px;font-weight:800;font-size:18px;}
.cs-stat span small{display:block;font-size:11.5px;font-weight:600;color:#F0C08A;letter-spacing:.04em;}
.cs-media{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1fr);gap:18px;align-items:center;}
.cs-media > img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:18px;box-shadow:0 18px 36px -22px rgba(22,24,41,.6);}
.cs-stack{display:flex;flex-direction:column;gap:12px;min-width:0;}
.cs-card.num{flex-direction:row;align-items:flex-start;gap:12px;}
.cs-card.num > div{display:flex;flex-direction:column;gap:4px;min-width:0;}
.cs-card.num .cs-ic{background:var(--orange);color:#fff;font-weight:800;font-size:18px;font-family:'Fraunces',Georgia,serif;}
.cs-card.num.dark .cs-ic{background:#F0C08A;color:var(--navy);}
.cs-card.num p{font-size:15px;color:var(--ink);} .cs-card.num.dark p{color:rgba(255,255,255,.9);}
.cs-col{display:flex;flex-direction:column;gap:10px;min-width:0;}
.cs-arrow{align-self:center;color:var(--orange);font-size:22px;font-weight:800;line-height:1;margin:-4px 0;}
.cs-paras{display:flex;flex-direction:column;gap:6px;}
.cs-card u{text-decoration-thickness:2px;text-underline-offset:2px;}
.cs-pages{align-items:center;}
.cs-page{margin:0;width:100%;display:flex;justify-content:center;}
.cs-page img{display:block;width:auto;max-width:min(100%,1280px);max-height:calc(100vh - 330px);min-height:180px;height:auto;aspect-ratio:16/9;border-radius:12px;box-shadow:0 14px 34px -20px rgba(22,24,41,.55);background:#fff;}
.cs-cover{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);gap:18px;align-items:stretch;}
.cs-cover .cs-hero{position:relative;min-height:52vh;justify-content:flex-end;padding-top:96px;}
.cs-cover .cs-logo{position:absolute;top:20px;left:22px;width:78px;height:auto;}
.cs-hero .cs-big.caps{font-family:inherit;font-style:italic;font-weight:800;text-transform:uppercase;letter-spacing:.04em;line-height:1.2;font-size:clamp(20px,2.3vw,34px);overflow-wrap:normal;}
.cs-doc{display:flex;align-items:center;justify-content:center;}
.cs-doc .cs-figs{display:flex;justify-content:center;width:100%;}
.cs-doc .cs-fig img{border:6px solid var(--orange);border-radius:4px;max-height:60vh;width:auto;}
.cs-hero.photo{background:linear-gradient(100deg,rgba(22,24,41,.96) 0%,rgba(22,24,41,.85) 45%,rgba(22,24,41,.25) 100%),var(--img) right center/cover no-repeat;}
@media (max-width:760px){ .cs-cover{grid-template-columns:1fr;} .cs-cover .cs-hero{min-height:30vh;} .cs-media{grid-template-columns:1fr;} .cs-media > img{order:-1;aspect-ratio:16/7;} .cs-hero.photo{background:linear-gradient(rgba(22,24,41,.88),rgba(22,24,41,.88)),var(--img) center/cover no-repeat;} }
/* Full screen and the slides window: a deck page fills the whole screen. No width cap, no presenter
   column, and everything scales with the screen (the sizes below are in em of .cs). */
.lesson-stage:fullscreen .stage-body:has(.cs), #audienceRoot .stage-body:has(.cs){grid-template-columns:minmax(0,1fr) !important;}
.lesson-stage:fullscreen .stage-body:has(.cs) .stage-presenter, #audienceRoot .stage-body:has(.cs) .stage-presenter{display:none !important;}
.lesson-stage:fullscreen #lessonSlideWrap:has(.cs), #audienceRoot #lessonSlideWrap:has(.cs){align-items:stretch !important;}
.lesson-stage:fullscreen #lessonSlideWrap:has(.cs) > *, #audienceRoot #lessonSlideWrap:has(.cs) > *{max-width:none !important;width:100% !important;}
.lesson-stage:fullscreen .lesson-card:has(.cs), #audienceRoot .lesson-card:has(.cs){max-width:none !important;width:100%;flex:1 1 auto;display:flex;flex-direction:column;justify-content:center;box-sizing:border-box;}
.lesson-stage:fullscreen .cs, #audienceRoot .cs{font-size:clamp(17px,1.32vw,32px);gap:clamp(14px,1.3vw,30px);}
.lesson-stage:fullscreen .cs-lead, #audienceRoot .cs-lead{font-size:1.18em;max-width:none;}
.lesson-stage:fullscreen .cs-label, #audienceRoot .cs-label{font-size:.72em;}
.lesson-stage:fullscreen .cs-sub, #audienceRoot .cs-sub{font-size:.8em;}
.lesson-stage:fullscreen .cs-grid, #audienceRoot .cs-grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,14em),1fr));gap:.9em;}
.lesson-stage:fullscreen .cs-grid.c2, #audienceRoot .cs-grid.c2{grid-template-columns:repeat(auto-fit,minmax(min(100%,19em),1fr));}
.lesson-stage:fullscreen .cs-grid.c3, #audienceRoot .cs-grid.c3{grid-template-columns:repeat(auto-fit,minmax(min(100%,15em),1fr));}
.lesson-stage:fullscreen .cs-card, #audienceRoot .cs-card{padding:.9em 1.1em;gap:.45em;}
.lesson-stage:fullscreen .cs-card .cs-ic, #audienceRoot .cs-card .cs-ic{width:2.1em;height:2.1em;font-size:1.25em;}
.lesson-stage:fullscreen .cs-card b, #audienceRoot .cs-card b{font-size:1.02em;}
.lesson-stage:fullscreen .cs-card p, .lesson-stage:fullscreen .cs-card li, #audienceRoot .cs-card p, #audienceRoot .cs-card li{font-size:.92em;}
.lesson-stage:fullscreen .cs-flow, #audienceRoot .cs-flow{grid-template-columns:repeat(auto-fit,minmax(min(100%,10em),1fr));gap:.7em;}
.lesson-stage:fullscreen .cs-flow li, #audienceRoot .cs-flow li{font-size:.92em;padding:2.6em .8em .8em;}
.lesson-stage:fullscreen .cs-flow li span, #audienceRoot .cs-flow li span{font-size:.88em;}
.lesson-stage:fullscreen .cs-list li, #audienceRoot .cs-list li, .lesson-stage:fullscreen .cs-do li, .lesson-stage:fullscreen .cs-dont li, #audienceRoot .cs-do li, #audienceRoot .cs-dont li{font-size:.95em;}
.lesson-stage:fullscreen .cs-list.two, #audienceRoot .cs-list.two{grid-template-columns:repeat(auto-fit,minmax(min(100%,17em),1fr));}
.lesson-stage:fullscreen .cs-split, #audienceRoot .cs-split{grid-template-columns:repeat(auto-fit,minmax(min(100%,19em),1fr));}
.lesson-stage:fullscreen .cs-tip, .lesson-stage:fullscreen .cs-warn, .lesson-stage:fullscreen .cs-note, #audienceRoot .cs-tip, #audienceRoot .cs-warn, #audienceRoot .cs-note{font-size:.95em;}
.lesson-stage:fullscreen .cs-table, #audienceRoot .cs-table{font-size:.88em;} .lesson-stage:fullscreen .cs-table th, #audienceRoot .cs-table th{font-size:.9em;}
.lesson-stage:fullscreen .cs-figs, #audienceRoot .cs-figs{grid-template-columns:repeat(auto-fit,minmax(min(100%,17em),1fr));}
.lesson-stage:fullscreen .cs-fig img, #audienceRoot .cs-fig img{max-height:72vh;}
.lesson-stage:fullscreen .cs-fig figcaption, #audienceRoot .cs-fig figcaption{font-size:.8em;}
.lesson-stage:fullscreen .cs-hero, #audienceRoot .cs-hero{min-height:60vh;padding:2em 2.2em;}
.lesson-stage:fullscreen .cs-hero p, #audienceRoot .cs-hero p{font-size:1.1em;max-width:none;}
.lesson-stage:fullscreen .cs-hero .cs-big, #audienceRoot .cs-hero .cs-big{font-size:clamp(34px,3.6vw,72px);}
.lesson-stage:fullscreen .cs-stat span, #audienceRoot .cs-stat span{font-size:1.15em;}
.lesson-stage:fullscreen .cs-cover .cs-hero, #audienceRoot .cs-cover .cs-hero{min-height:74vh;}
.lesson-stage:fullscreen .cs-page img, #audienceRoot .cs-page img{max-width:none;width:auto;max-height:86vh;max-width:100%;border-radius:6px;}
.lesson-stage:fullscreen .cs-hero .cs-big.caps, #audienceRoot .cs-hero .cs-big.caps{font-size:clamp(26px,2.5vw,56px);}
.lesson-stage:fullscreen .cs-cover .cs-logo, #audienceRoot .cs-cover .cs-logo{width:6.5em;}
.lesson-stage:fullscreen .cs-doc .cs-fig img, #audienceRoot .cs-doc .cs-fig img{max-height:80vh;}
.lesson-stage:fullscreen .cs-media, #audienceRoot .cs-media{gap:1.3em;}
.lesson-stage:fullscreen .cs-media > img, #audienceRoot .cs-media > img{max-height:70vh;}
.lesson-stage:fullscreen .cs-stack, #audienceRoot .cs-stack{gap:.8em;}
.lesson-stage:fullscreen .cs-card.num p, #audienceRoot .cs-card.num p{font-size:1em;}
.lesson-stage:fullscreen .cs-card.num .cs-ic, #audienceRoot .cs-card.num .cs-ic{font-size:1.15em;}
#csZoom{position:fixed;inset:0;z-index:9500;background:rgba(10,12,24,.86);display:flex;align-items:center;justify-content:center;padding:24px;cursor:zoom-out;}
#csZoom img{max-width:96vw;max-height:94vh;border-radius:8px;background:#fff;box-shadow:0 20px 60px rgba(0,0,0,.5);}
@media (max-width:640px){ .cs-lead{font-size:16px;} .cs-flow li:not(:last-child)::after{display:none;} .cs-hero{padding:22px 18px;} }
`;
const st = document.createElement("style"); st.id = "ft-slides"; st.textContent = css; document.head.appendChild(st);
// Document images open full size on click (Esc or a click closes).
document.addEventListener("click", function(e){
  const img = e.target.closest && e.target.closest(".cs-fig img");
  const zoom = document.getElementById("csZoom");
  if(zoom && (e.target === zoom || e.target.closest("#csZoom"))){ zoom.remove(); return; }
  if(!img) return;
  const z = document.createElement("div"); z.id = "csZoom"; z.innerHTML = `<img src="${img.getAttribute("src")}" alt="">`;
  document.body.appendChild(z);
});
document.addEventListener("keydown", function(e){ if(e.key === "Escape"){ const z = document.getElementById("csZoom"); if(z) z.remove(); } });
})();
