/* ============================================================
   Native lesson slides: the visual design for lessons rebuilt from their
   Canva decks (each deck page is one slide, with the deck's exact wording).
   Slide HTML is generated by build/slides/make_lesson.py into
   build/lessons/lessonNN.js; these are its components:
     .cs-label   the deck's section label (e.g. CLAIM FILING)
     .cs-lead    the page's main statement
     .cs-grid / .cs-card   icon cards (.cs-card.dark, .cs-card.soft)
     .cs-flow    numbered steps with connectors
     .cs-list    a list with icons (check, dot, step numbers)
     .cs-do / .cs-dont     ✅ correct / ❌ do not boxes
     .cs-tip, .cs-warn     callouts
     .cs-table   a table
     .cs-fig     a document image: click to see it full size
     .cs-hero    title and closing slides (.photo: over the deck's photo)
     .cs-media   the points beside the deck page's photo; .cs-card.num a numbered point
     .cs-pages   a deck page shown as its own image (build/slides/image_lesson.py)
     .cs-cover   a correspondence slide: the title on the deck's photo beside the document (orange frame)
   In full screen and the slides window a page fills the screen: no width cap, no presenter
   column, and the text scales with the screen.
   Loaded after js/ft-updates.js.
   ============================================================ */
(function(){
const css = `
.cs{display:flex;flex-direction:column;gap:14px;font-size:15.5px;line-height:1.55;color:var(--ink);}
/* the slide stage styles lesson text bold and centered: these slides set their own */
.ft-body .cs p, .ft-body .cs li, .ft-body .cs td{font-weight:400 !important;text-align:left !important;}
.ft-body .cs .cs-lead{font-weight:500 !important;}
.ft-body .cs b{font-weight:700;}
.ft-body .cs ul{text-align:left;}
.ft-body .cs .cs-flow li{text-align:center !important;font-weight:700 !important;}
.ft-body .cs .cs-flow li span{font-weight:500;}
.ft-body .cs .cs-hero p{color:rgba(255,255,255,.88);}
.ft-body .cs{font-weight:400;} .ft-body .cs p{margin:0 !important;}
.ft-body .cs .cs-list li, .ft-body .cs .cs-flow li{margin:0 !important;list-style:none;}
.ft-body .cs .cs-list li{padding:8px 12px 8px 40px !important;}
.ft-body .cs .cs-list li::before, .ft-body .cs .cs-flow li::before{position:absolute !important;display:flex !important;margin:0 !important;vertical-align:baseline !important;}
.ft-body .cs .cs-list li::before{left:10px !important;top:8px !important;width:20px !important;height:20px !important;}
.ft-body .cs .cs-list.dot li::before{left:17px !important;top:15px !important;width:8px !important;height:8px !important;}
.ft-body .cs .cs-flow li::before{top:10px !important;left:50% !important;width:24px !important;height:24px !important;}
/* a tall slide scrolls inside the card instead of being cut off */
.lesson-card.ft-section:has(.cs){overflow-y:auto;}
.cs-label{align-self:flex-start;display:inline-flex;align-items:center;gap:6px;font-size:11.5px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:var(--orange-deep);background:#FBF1E6;border:1px solid #F0D2AE;border-radius:999px;padding:4px 12px;}
.cs-lead{font-size:16.5px;line-height:1.6;color:var(--ink);margin:0;max-width:78ch;}
.cs-lead b, .cs p b{color:var(--navy);}
.cs-sub{font-size:12.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--navy);margin:4px 0 -4px;}
.cs p{margin:0;}
.cs-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:12px;}
.cs-grid.c2{grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));}
.cs-grid.c3{grid-template-columns:repeat(auto-fit,minmax(min(100%,230px),1fr));}
.cs-card{position:relative;background:#fff;border:1px solid var(--line);border-radius:16px;padding:12px 14px;box-shadow:0 1px 2px rgba(22,24,41,.04),0 10px 24px -18px rgba(22,24,41,.35);display:flex;flex-direction:column;gap:6px;min-width:0;}
.cs-card .cs-ic{width:34px;height:34px;border-radius:12px;display:flex;align-items:center;justify-content:center;font-size:20px;background:#FBF1E6;flex-shrink:0;}
.cs-card b{font-size:15px;color:var(--navy);line-height:1.35;}
.cs-card p, .cs-card li{font-size:14px;color:var(--ink-soft);line-height:1.5;}
.cs-card ul{margin:2px 0 0;padding-left:18px;} .cs-card li{margin:2px 0;}
.cs-card.dark{background:linear-gradient(145deg,var(--navy),var(--navy-soft));border-color:transparent;color:#fff;}
.cs-card.dark b{color:#F0C08A;} .cs-card.dark p, .cs-card.dark li{color:rgba(255,255,255,.86);}
.cs-card.dark .cs-ic{background:rgba(240,192,138,.16);}
.cs-card.soft{background:#F6F7FB;box-shadow:none;}
.cs-card.accent{border-top:4px solid var(--orange);}
.cs-card .cs-tag{align-self:flex-start;font-size:11px;font-weight:800;letter-spacing:.06em;border-radius:999px;padding:2px 9px;background:var(--navy);color:#fff;}
.cs-card .cs-tag.o{background:var(--orange);}
.cs-flow{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,150px),1fr));gap:10px;counter-reset:cs;}
.cs-flow li{counter-increment:cs;position:relative;background:#fff;border:1px solid var(--line);border-radius:14px;padding:38px 12px 12px;font-size:14px;font-weight:700;color:var(--navy);text-align:center;line-height:1.35;}
.cs-flow li::before{content:counter(cs);position:absolute;top:10px;left:50%;transform:translateX(-50%);width:24px;height:24px;border-radius:50%;background:var(--orange);color:#fff;font-size:12.5px;font-weight:800;display:flex;align-items:center;justify-content:center;}
.cs-flow li:not(:last-child)::after{content:"→";position:absolute;right:-10px;top:50%;transform:translateY(-50%);width:18px;height:18px;border-radius:50%;background:var(--navy);color:#fff;font-size:11px;display:flex;align-items:center;justify-content:center;z-index:1;}
.cs-flow li span{display:block;font-size:12.5px;font-weight:500;color:var(--ink-soft);margin-top:4px;}
.cs-list{list-style:none;margin:0;padding:0;display:grid;gap:8px;}
.cs-list li{position:relative;padding:8px 12px 8px 40px;background:#fff;border:1px solid var(--line);border-radius:12px;font-size:14.5px;line-height:1.5;}
.cs-list li::before{content:"✓";position:absolute;left:10px;top:8px;width:20px;height:20px;border-radius:50%;background:var(--success-bg);color:var(--success);font-size:12px;font-weight:800;display:flex;align-items:center;justify-content:center;}
.cs-list.dot li::before{content:"";width:8px;height:8px;left:17px;top:15px;background:var(--orange);}
.cs-list.num{counter-reset:csl;} .cs-list.num li{counter-increment:csl;}
.cs-list.num li::before{content:counter(csl);background:var(--navy);color:#fff;}
.cs-list.two{grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));}
.cs-list li b{color:var(--navy);}
.cs-split{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:14px;align-items:start;}
.cs-do, .cs-dont{border-radius:14px;padding:12px 16px;}
.cs-do{background:var(--success-bg);border:1px solid #BFD9C8;} .cs-dont{background:var(--danger-bg);border:1px solid #E7C3BD;}
.cs-do > b, .cs-dont > b{display:block;font-size:13px;font-weight:800;letter-spacing:.04em;margin-bottom:6px;}
.cs-do > b{color:var(--success);} .cs-dont > b{color:var(--danger);}
.cs-do ul, .cs-dont ul{margin:0;padding-left:18px;} .cs-do li, .cs-dont li{margin:3px 0;font-size:14.5px;}
.cs-tip, .cs-warn, .cs-note{display:flex;gap:10px;align-items:flex-start;border-radius:14px;padding:12px 16px;font-size:14.5px;line-height:1.5;}
.cs-tip{background:#FBF1E6;border-left:4px solid var(--orange);}
.cs-warn{background:var(--danger-bg);border-left:4px solid var(--danger);}
.cs-note{background:#EEF1F8;border-left:4px solid var(--navy);}
.cs-tip::before{content:"💡";} .cs-warn::before{content:"⚠️";} .cs-note::before{content:"📌";}
.cs-table{width:100%;border-collapse:separate;border-spacing:0;font-size:13.5px;border:1px solid var(--line);border-radius:14px;overflow:hidden;background:#fff;}
.cs-table th{background:var(--navy);color:#fff;text-align:left;font-weight:700;padding:9px 12px;font-size:12.5px;letter-spacing:.02em;}
.cs-table td{padding:8px 12px;border-top:1px solid var(--line);vertical-align:top;}
.cs-table tr:nth-child(even) td{background:#F8F9FC;}
.cs-table td:first-child{font-weight:700;color:var(--navy);}
.cs-tablewrap{overflow-x:auto;border-radius:14px;}
.cs-fig{margin:0;display:flex;flex-direction:column;align-items:center;gap:6px;}
.cs-figs{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:14px;align-items:start;}
.cs-fig img{max-width:100%;max-height:52vh;border-radius:10px;border:1px solid var(--line);box-shadow:0 12px 28px -18px rgba(22,24,41,.5);cursor:zoom-in;background:#fff;}
.cs-fig figcaption{font-size:12.5px;color:var(--ink-soft);font-weight:600;}
.cs-hero{min-height:44vh;display:flex;flex-direction:column;justify-content:center;gap:12px;padding:28px 30px;border-radius:18px;background:radial-gradient(circle at 85% 20%,rgba(219,132,55,.35),transparent 45%),linear-gradient(140deg,var(--navy-deep),var(--navy));color:#fff;}
.cs-hero .cs-label{background:rgba(240,192,138,.14);border-color:rgba(240,192,138,.4);color:#F0C08A;}
.cs-hero .cs-big{font-family:'Fraunces',Georgia,serif;font-size:clamp(28px,4vw,44px);font-weight:700;line-height:1.15;color:#fff;}
.cs-hero p{font-size:17px;color:rgba(255,255,255,.88);max-width:62ch;}
.cs-stat{display:flex;flex-wrap:wrap;gap:10px;}
.cs-stat span{background:var(--navy);color:#fff;border-radius:12px;padding:10px 14px;font-weight:800;font-size:18px;}
.cs-stat span small{display:block;font-size:11.5px;font-weight:600;color:#F0C08A;letter-spacing:.04em;}
.cs-media{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,1fr);gap:18px;align-items:center;}
.cs-media > img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:18px;box-shadow:0 18px 36px -22px rgba(22,24,41,.6);}
.cs-stack{display:flex;flex-direction:column;gap:12px;min-width:0;}
.cs-card.num{flex-direction:row;align-items:flex-start;gap:12px;}
.cs-card.num > div{display:flex;flex-direction:column;gap:4px;min-width:0;}
.cs-card.num .cs-ic{background:var(--orange);color:#fff;font-weight:800;font-size:18px;font-family:'Fraunces',Georgia,serif;}
.cs-card.num.dark .cs-ic{background:#F0C08A;color:var(--navy);}
.cs-card.num p{font-size:15px;color:var(--ink);} .cs-card.num.dark p{color:rgba(255,255,255,.9);}
.cs-col{display:flex;flex-direction:column;gap:10px;min-width:0;}
.cs-arrow{align-self:center;color:var(--orange);font-size:22px;font-weight:800;line-height:1;margin:-4px 0;}
.cs-paras{display:flex;flex-direction:column;gap:6px;}
.cs-card u{text-decoration-thickness:2px;text-underline-offset:2px;}
.cs-pages{align-items:center;}
/* A lesson of deck pages (body.ft-fit): the controls sit in a column to the right of the slide, so the
   slide and its Previous / Next bar fit on one screen (fitPages() below sizes the page to what's left). */
@media (min-width:1000px){
  body.ft-fit main:has(#lessonStage){display:flow-root;padding-top:12px;}
  body.ft-fit main:has(#lessonStage) > *:not(#lessonStage){float:right;clear:right;width:200px;margin:0 0 10px;}
  body.ft-fit main:has(#lessonStage) > #lessonStage{margin:0 216px 0 0;}
  body.ft-fit main:has(#lessonStage) > #navBackSlot:empty{display:none;}
  /* the footer line about an inch under the slide, and the page ends there */
  body.ft-fit main:has(#lessonStage){padding-bottom:62px;}
  body.ft-fit main:has(#lessonStage) + .footer-note{padding:24px 24px 10px;}
  body.ft-fit .day-head-compact{display:flex;flex-direction:column;gap:4px;border:0;padding:0;}
  body.ft-fit .day-head-compact .dhc-title{white-space:normal;font-size:17px;line-height:1.3;}
  body.ft-fit .ls-top{display:flex;flex-direction:column;align-items:stretch;gap:8px;}
  body.ft-fit .ls-top > *, body.ft-fit .ls-top .btn{width:100%;margin:0 !important;justify-content:center;}
  body.ft-fit .ls-top .audio-bar{display:grid;grid-template-columns:1fr auto;gap:6px;}
  body.ft-fit .ls-top .audio-bar #audioModeBtn{grid-column:1 / -1;}
  body.ft-fit .ls-top .or-tip{font-size:12px;line-height:1.4;order:9;white-space:normal;}
}
/* Every slide of a deck-page lesson is the same size (the standard size): nothing on one slide takes room
   the others don't. The progress dots stay on one row however many slides the lesson has (a long lesson's
   dots get narrower), and the last slide's "That's everything for this lesson" banner isn't shown (its
   Finish lesson button says the same). */
body.ft-fit .lesson-stage .slide-dots{flex-wrap:nowrap;gap:4px;overflow:hidden;padding:0 4px;}
body.ft-fit .lesson-stage .slide-dot{flex:0 1 10px;min-width:3px;}
body.ft-fit .lesson-stage .slide-dot.active{flex:0 0 22px;}
body.ft-fit .lesson-stage .slide-done-banner{display:none;}
/* No white frame around the deck page: the page sits straight on the lesson panel, in the middle, across and
   down (the frame and its card are see-through, without the orange strip on top). */
body.ft-fit #lessonSlideWrap{background:transparent !important;border:0 !important;box-shadow:none !important;display:flex !important;flex-direction:column;justify-content:center;align-items:center;}
body.ft-fit #lessonSlideWrap::before{display:none !important;}
/* the page in the middle of the lesson panel: the frame takes the panel's whole width, and the presenter
   character stands in the bottom-right corner over it (beside the page, which is narrower than the frame) */
body.ft-fit #lessonStage:not(:fullscreen) .stage-body{display:block !important;position:relative;}
body.ft-fit #lessonStage:not(:fullscreen) .stage-presenter{position:absolute !important;right:0;bottom:0;margin:0 !important;z-index:2;width:clamp(110px, 11%, 170px) !important;height:auto !important;}
body.ft-fit #lessonSlideWrap > .card.lesson-card{background:transparent !important;border:0 !important;box-shadow:none !important;width:100%;margin:0 auto !important;}
body.ft-fit #lessonSlideWrap .ft-body{display:flex;justify-content:center;}
/* the lesson page (not full screen): every slide's frame and page image get the one size fitPages() keeps */
body.ft-fit #lessonStage:not(:fullscreen) #lessonSlideWrap{height:var(--ft-frame-h, auto);}
body.ft-fit #lessonStage:not(:fullscreen) .cs-page img{max-height:var(--ft-img-h, calc(100vh - 330px));max-width:100%;
  width:min(100%, calc(var(--ft-img-h, calc(100vh - 330px)) * 16 / 9));height:auto;}   /* its size before the picture has loaded */
.cs-page{margin:0;width:100%;display:flex;justify-content:center;}
.cs-page img{display:block;width:auto;max-width:min(100%,1280px);max-height:calc(100vh - 330px);min-height:180px;height:auto;aspect-ratio:16/9;border-radius:12px;box-shadow:0 14px 34px -20px rgba(22,24,41,.55);background:rgba(22,24,41,.06);}
/* No blink between slides: in a deck-page lesson and the Orientation, the next slide simply replaces the one
   shown (like a slideshow). The page doesn't fade in on each render, nor the slide or its page parts. */
body.ft-fit main, body.ft-orient main{animation:none !important;}
body.ft-fit #lessonSlideWrap, body.ft-orient #lessonSlideWrap,
body.ft-fit #lessonSlideWrap.pg-anim > *, body.ft-orient #lessonSlideWrap.pg-anim > *{animation:none !important;}
.cs-cover{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(0,1fr);gap:18px;align-items:stretch;}
.cs-cover .cs-hero{position:relative;min-height:52vh;justify-content:flex-end;padding-top:96px;}
.cs-cover .cs-logo{position:absolute;top:20px;left:22px;width:78px;height:auto;}
.cs-hero .cs-big.caps{font-family:inherit;font-style:italic;font-weight:800;text-transform:uppercase;letter-spacing:.04em;line-height:1.2;font-size:clamp(20px,2.3vw,34px);overflow-wrap:normal;}
.cs-doc{display:flex;align-items:center;justify-content:center;}
.cs-doc .cs-figs{display:flex;justify-content:center;width:100%;}
.cs-doc .cs-fig img{border:6px solid var(--orange);border-radius:4px;max-height:60vh;width:auto;}
.cs-hero.photo{background:linear-gradient(100deg,rgba(22,24,41,.96) 0%,rgba(22,24,41,.85) 45%,rgba(22,24,41,.25) 100%),var(--img) right center/cover no-repeat;}
@media (max-width:760px){ .cs-cover{grid-template-columns:1fr;} .cs-cover .cs-hero{min-height:30vh;} .cs-media{grid-template-columns:1fr;} .cs-media > img{order:-1;aspect-ratio:16/7;} .cs-hero.photo{background:linear-gradient(rgba(22,24,41,.88),rgba(22,24,41,.88)),var(--img) center/cover no-repeat;} }
/* Full screen and the slides window: a deck page fills the whole screen. No width cap, no presenter
   column, and everything scales with the screen (the sizes below are in em of .cs). */
.lesson-stage:fullscreen .stage-body:has(.cs), #audienceRoot .stage-body:has(.cs){grid-template-columns:minmax(0,1fr) !important;}
.lesson-stage:fullscreen .stage-body:has(.cs) .stage-presenter, #audienceRoot .stage-body:has(.cs) .stage-presenter{display:none !important;}
.lesson-stage:fullscreen #lessonSlideWrap:has(.cs), #audienceRoot #lessonSlideWrap:has(.cs){align-items:stretch !important;}
.lesson-stage:fullscreen #lessonSlideWrap:has(.cs) > *, #audienceRoot #lessonSlideWrap:has(.cs) > *{max-width:none !important;width:100% !important;}
.lesson-stage:fullscreen .lesson-card:has(.cs), #audienceRoot .lesson-card:has(.cs){max-width:none !important;width:100%;flex:1 1 auto;display:flex;flex-direction:column;justify-content:center;box-sizing:border-box;}
.lesson-stage:fullscreen .cs, #audienceRoot .cs{font-size:clamp(17px,1.32vw,32px);gap:clamp(14px,1.3vw,30px);}
.lesson-stage:fullscreen .cs-lead, #audienceRoot .cs-lead{font-size:1.18em;max-width:none;}
.lesson-stage:fullscreen .cs-label, #audienceRoot .cs-label{font-size:.72em;}
.lesson-stage:fullscreen .cs-sub, #audienceRoot .cs-sub{font-size:.8em;}
.lesson-stage:fullscreen .cs-grid, #audienceRoot .cs-grid{grid-template-columns:repeat(auto-fit,minmax(min(100%,14em),1fr));gap:.9em;}
.lesson-stage:fullscreen .cs-grid.c2, #audienceRoot .cs-grid.c2{grid-template-columns:repeat(auto-fit,minmax(min(100%,19em),1fr));}
.lesson-stage:fullscreen .cs-grid.c3, #audienceRoot .cs-grid.c3{grid-template-columns:repeat(auto-fit,minmax(min(100%,15em),1fr));}
.lesson-stage:fullscreen .cs-card, #audienceRoot .cs-card{padding:.9em 1.1em;gap:.45em;}
.lesson-stage:fullscreen .cs-card .cs-ic, #audienceRoot .cs-card .cs-ic{width:2.1em;height:2.1em;font-size:1.25em;}
.lesson-stage:fullscreen .cs-card b, #audienceRoot .cs-card b{font-size:1.02em;}
.lesson-stage:fullscreen .cs-card p, .lesson-stage:fullscreen .cs-card li, #audienceRoot .cs-card p, #audienceRoot .cs-card li{font-size:.92em;}
.lesson-stage:fullscreen .cs-flow, #audienceRoot .cs-flow{grid-template-columns:repeat(auto-fit,minmax(min(100%,10em),1fr));gap:.7em;}
.lesson-stage:fullscreen .cs-flow li, #audienceRoot .cs-flow li{font-size:.92em;padding:2.6em .8em .8em;}
.lesson-stage:fullscreen .cs-flow li span, #audienceRoot .cs-flow li span{font-size:.88em;}
.lesson-stage:fullscreen .cs-list li, #audienceRoot .cs-list li, .lesson-stage:fullscreen .cs-do li, .lesson-stage:fullscreen .cs-dont li, #audienceRoot .cs-do li, #audienceRoot .cs-dont li{font-size:.95em;}
.lesson-stage:fullscreen .cs-list.two, #audienceRoot .cs-list.two{grid-template-columns:repeat(auto-fit,minmax(min(100%,17em),1fr));}
.lesson-stage:fullscreen .cs-split, #audienceRoot .cs-split{grid-template-columns:repeat(auto-fit,minmax(min(100%,19em),1fr));}
.lesson-stage:fullscreen .cs-tip, .lesson-stage:fullscreen .cs-warn, .lesson-stage:fullscreen .cs-note, #audienceRoot .cs-tip, #audienceRoot .cs-warn, #audienceRoot .cs-note{font-size:.95em;}
.lesson-stage:fullscreen .cs-table, #audienceRoot .cs-table{font-size:.88em;} .lesson-stage:fullscreen .cs-table th, #audienceRoot .cs-table th{font-size:.9em;}
.lesson-stage:fullscreen .cs-figs, #audienceRoot .cs-figs{grid-template-columns:repeat(auto-fit,minmax(min(100%,17em),1fr));}
.lesson-stage:fullscreen .cs-fig img, #audienceRoot .cs-fig img{max-height:72vh;}
.lesson-stage:fullscreen .cs-fig figcaption, #audienceRoot .cs-fig figcaption{font-size:.8em;}
.lesson-stage:fullscreen .cs-hero, #audienceRoot .cs-hero{min-height:60vh;padding:2em 2.2em;}
.lesson-stage:fullscreen .cs-hero p, #audienceRoot .cs-hero p{font-size:1.1em;max-width:none;}
.lesson-stage:fullscreen .cs-hero .cs-big, #audienceRoot .cs-hero .cs-big{font-size:clamp(34px,3.6vw,72px);}
.lesson-stage:fullscreen .cs-stat span, #audienceRoot .cs-stat span{font-size:1.15em;}
.lesson-stage:fullscreen .cs-cover .cs-hero, #audienceRoot .cs-cover .cs-hero{min-height:74vh;}
.lesson-stage:fullscreen .cs-page img, #audienceRoot .cs-page img{max-width:none;width:auto;max-height:86vh;max-width:100%;border-radius:6px;}
.lesson-stage:fullscreen .cs-hero .cs-big.caps, #audienceRoot .cs-hero .cs-big.caps{font-size:clamp(26px,2.5vw,56px);}
.lesson-stage:fullscreen .cs-cover .cs-logo, #audienceRoot .cs-cover .cs-logo{width:6.5em;}
.lesson-stage:fullscreen .cs-doc .cs-fig img, #audienceRoot .cs-doc .cs-fig img{max-height:80vh;}
.lesson-stage:fullscreen .cs-media, #audienceRoot .cs-media{gap:1.3em;}
.lesson-stage:fullscreen .cs-media > img, #audienceRoot .cs-media > img{max-height:70vh;}
.lesson-stage:fullscreen .cs-stack, #audienceRoot .cs-stack{gap:.8em;}
.lesson-stage:fullscreen .cs-card.num p, #audienceRoot .cs-card.num p{font-size:1em;}
.lesson-stage:fullscreen .cs-card.num .cs-ic, #audienceRoot .cs-card.num .cs-ic{font-size:1.15em;}
#csZoom{position:fixed;inset:0;z-index:9500;background:rgba(10,12,24,.86);display:flex;align-items:center;justify-content:center;padding:24px;cursor:zoom-out;}
#csZoom img{max-width:96vw;max-height:94vh;border-radius:8px;background:#fff;box-shadow:0 20px 60px rgba(0,0,0,.5);}
@media (max-width:640px){ .cs-lead{font-size:16px;} .cs-flow li:not(:last-child)::after{display:none;} .cs-hero{padding:22px 18px;} }
`;
const st = document.createElement("style"); st.id = "ft-slides"; st.textContent = css; document.head.appendChild(st);
// A deck page (.cs-page) is sized to the room it has, so nothing needs scrolling: on the lesson page the
// whole page fits the screen (the slide, its Previous / Next bar and, about an inch below, the footer line);
// in full screen and the slides window, the slide and the bar fit. It runs after each render and again once
// the slide has slid in (measured mid-animation, positions are off), and on resize and full screen.
function fitPages(){
  const d = typeof state !== "undefined" && state.view === "day" && typeof DAYS !== "undefined" ? DAYS.find(x=>x.id===state.dayId) : null;
  document.body.classList.toggle("ft-fit", !!(d && (d.sections||[]).some(x=>/class="cs cs-pages"/.test(x.html))));
  document.body.classList.toggle("ft-orient", !!(d && window.FT_ORIENTATION && d.id === window.FT_ORIENTATION.id));   // its slides' background (ft-rules.js)
  if(document.body.classList.contains("ft-orient")){   // the band's label and title (drawn by the slide: ft-rules.js)
    const w = document.getElementById("lessonSlideWrap"), k = w && w.querySelector(":scope > .topic-separator"), t = w && w.querySelector(":scope > .card > h4");
    // the room the band takes, in px from the slide's width (on the slide's padding, which the engine's
    // fit-zoom doesn't scale, so zoomed content never rises into the band)
    if(w){ const band = Math.round(w.offsetWidth * 0.113 + 10) + "px"; if(w.style.getPropertyValue("--ftr-band") !== band) w.style.setProperty("--ftr-band", band); }
    if(w && t){ const kt = (k ? k.textContent : "").replace(/\s+/g, " ").trim(), h = t.cloneNode(true); h.querySelectorAll(".lnum").forEach(n=>n.remove());   // the label already says "Part N of 19"
      const tt = h.textContent.replace(/\s+/g, " ").trim();
      if(w.dataset.kicker !== kt) w.dataset.kicker = kt; if(w.dataset.title !== tt) w.dataset.title = tt; }
  }
  const img = document.querySelector(".cs-page img");
  if(!img && !document.body.classList.contains("ft-fit")) return;
  // the slide frame: the page image's, or a topic divider's (the same size, so slides don't change size)
  const frame = img ? img.closest(".lesson-slide") : document.querySelector("#lessonStage .lesson-slide, #audienceRoot .lesson-slide"); if(!frame) return;
  const stage = frame.closest(".lesson-stage, #audienceRoot"), nav = stage && stage.querySelector(".slide-nav");
  const pad = parseFloat(getComputedStyle(frame).paddingBottom) || 0;
  const page = !document.fullscreenElement && !frame.closest("#audienceRoot");
  // On the lesson page the slide frame takes the height the screen has left above the footer line
  // (the portal gives it 66% of the screen, whatever else is on the page).
  const foot = page && document.body.classList.contains("ft-fit") && document.querySelector(".footer-note");
  if(foot && frame && stage){
    // One size for every slide: the frame's height is kept in --ft-frame-h on the page (it outlives each
    // slide's render), and the page image is sized from it by CSS (--ft-img-h), never by measuring the
    // image. Once it's set, moving between slides changes nothing, so slides don't flicker or come out
    // smaller; it's worked out again only when the screen changes size.
    // (the page stretches to the screen, so the footer's own place says nothing: count from the stage down)
    const root = document.documentElement, cs = getComputedStyle(frame);
    const main = stage.closest("main"), below = (main ? parseFloat(getComputedStyle(main).paddingBottom) || 0 : 0) + foot.offsetHeight;
    // measured from the layout (offsetTop / offsetHeight), which the slide-in animation doesn't move
    const docTop = el=>{ let y = 0; for(; el; el = el.offsetParent) y += el.offsetTop; return y; };
    const slack = window.innerHeight - 4 - (docTop(stage) + stage.offsetHeight + below);
    if(Math.abs(slack) > 2 || !root.style.getPropertyValue("--ft-frame-h")){
      const h = Math.max(320, Math.round(frame.offsetHeight + slack));
      root.style.setProperty("--ft-frame-h", h + "px");
      root.style.setProperty("--ft-img-h", Math.max(160, h - (parseFloat(cs.paddingTop) || 0) - pad) + "px");
    }
    if(frame.style.height) frame.style.height = "";
    if(img && img.style.maxHeight) img.style.maxHeight = "";
    if(window.scrollY && document.documentElement.scrollHeight <= window.innerHeight + 2) window.scrollTo(0, 0);
    return;
  } else if(frame && frame.style.height) frame.style.height = "";   // full screen / slides window: the frame fills the stage
  if(!img) return;
  for(let pass = 0; pass < 4; pass++){
    const r = img.getBoundingClientRect(), n = nav ? nav.getBoundingClientRect() : null;
    // positive: how far it runs under the bar or past the slide frame; negative: room to grow
    const over = Math.max(n ? r.bottom + 8 - n.top : -1e4, frame ? r.bottom + pad - frame.getBoundingClientRect().bottom : -1e4,
                          page ? -1e4 : (n ? n.bottom : r.bottom) + 10 - window.innerHeight);
    if(Math.abs(over) <= 2) break;
    const h = Math.max(160, Math.round(r.height - over));
    if(h === Math.round(r.height)) break;
    img.style.maxHeight = h + "px";
    if(over < 0 && Math.round(img.getBoundingClientRect().height) === Math.round(r.height)) break;   // at its widest already
  }
  // the whole lesson page fits now: show it from the top (the portal scrolls the slide under the top bar)
  if(page && document.body.classList.contains("ft-fit") && document.documentElement.scrollHeight <= window.innerHeight + 2 && window.scrollY) window.scrollTo(0, 0);
}
let fitQueued = false, fitLater = 0;
const queueFit = ()=>{
  if(!fitQueued){ fitQueued = true; requestAnimationFrame(()=>{ fitQueued = false; fitPages(); }); }
  clearTimeout(fitLater); fitLater = setTimeout(fitPages, 480);   // after the slide-in (0.4s)
};
// Sized as soon as a slide is put on the page (the observer runs before the browser draws it), so a lesson's
// first slide never shows for a frame at the default size; then again in the next frame and after the slide-in.
let fitBusy = false;
new MutationObserver(()=>{ if(fitBusy) return; fitBusy = true; try{ noRefade(); fitPages(); preloadNext(); } finally { fitBusy = false; } queueFit(); }).observe(document.body, {childList:true, subtree:true});
// The page fades in when you go to another page, not when the page you're on is drawn again. On first open
// the dashboard is drawn several times in a few seconds (progress, settings and sign-in arriving one by one),
// and each time its fade started from blank: the page blinked. The observer runs before the browser draws.
let lastPageKey = null;
function noRefade(){
  const m = document.querySelector("main"); if(!m || m.__ftSeen || typeof state === "undefined") return;
  m.__ftSeen = true;
  const key = [state.view, state.view === "day" ? state.dayId : "", state.view === "day" ? state.dayViewMode : ""].join(":");
  if(key === lastPageKey) m.style.animation = "none";
  lastPageKey = key;
}
// The next two slides' page images load while this one is shown, so Next never waits on a picture.
const preloaded = new Set();
function preloadNext(){
  const cur = document.querySelector(".cs-page img"); if(!cur || typeof state === "undefined" || typeof DAYS === "undefined") return;
  const d = DAYS.find(x=>x.id===state.dayId); if(!d) return;
  const srcs = (d.__ftImgs = d.__ftImgs || (d.sections||[]).map(x=>(String(x.html).match(/<img src="([^"]+\/slides\/[^"]+)"/)||[])[1]).filter(Boolean));
  const at = srcs.indexOf(cur.getAttribute("src"));
  for(const u of at < 0 ? [] : srcs.slice(at + 1, at + 3)) if(!preloaded.has(u)){ preloaded.add(u); const im = new Image(); im.decoding = "async"; im.src = u; }
}
// The Orientation slides' background is fetched with the page, so it's there the first time they open.
(new Image()).src = "/ft/orientation/background.webp";
window.addEventListener("resize", queueFit);
document.addEventListener("animationend", (e)=>{ if(e.target && e.target.id === "lessonSlideWrap") fitPages(); }, true);
document.addEventListener("fullscreenchange", ()=>setTimeout(fitPages, 60));
// Document images open full size on click (Esc or a click closes).
document.addEventListener("click", function(e){
  const img = e.target.closest && e.target.closest(".cs-fig img");
  const zoom = document.getElementById("csZoom");
  if(zoom && (e.target === zoom || e.target.closest("#csZoom"))){ zoom.remove(); return; }
  if(!img) return;
  const z = document.createElement("div"); z.id = "csZoom"; z.innerHTML = `<img src="${img.getAttribute("src")}" alt="">`;
  document.body.appendChild(z);
});
document.addEventListener("keydown", function(e){ if(e.key === "Escape"){ const z = document.getElementById("csZoom"); if(z) z.remove(); } });

/* ▶ Listen and 🎧 Audio mode: what a slide reads aloud.
   - A deck page shown as an image reads its spoken script (data-say, the page's text in reading order,
     written by build/slides/image_lesson.py).
   - Other slides read their text a box at a time: each heading, card, list item and table cell ends in a
     pause, so words from two boxes don't run together, and a title shown twice (a label over its heading)
     is read once. Emoji, arrows and bullets aren't read out, nor the slide's buttons and links.
   - Audio mode moves on from a slide with nothing to read instead of stopping there. */
const SAY_SKIP = ".pg-hide, .pg-badge, svg, .svg-diagram-card, .vis-flow, .vis-chips, .vis-label, .topic-separator, .fp-num, .lnum, .vis-badge, .vis-card-i, .qc-actions, .quiz-rationale:not(.show), button, a.btn, .actions, .canva-frame, iframe, .lx-panel:not([open])";
const SAY_BLOCK = "p, div, li, h1, h2, h3, h4, h5, h6, td, th, tr, dt, dd, figure, figcaption, section, blockquote, summary, table, ul, ol, br";
function ftSayLines(root){
  const pages = [...root.querySelectorAll(".cs-page[data-say]")].filter(f=>!f.closest(".pg-hide"));
  if(pages.length) return pages.map(f=>f.dataset.say).join("\n").split("\n");
  const c = root.cloneNode(true);
  c.querySelectorAll(SAY_SKIP).forEach(n=>n.remove());
  c.querySelectorAll(SAY_BLOCK).forEach(n=>{ n.before("\n"); n.after("\n"); });
  return c.textContent.split("\n");
}
function ftSayText(root){
  const out = [];
  for(let l of ftSayLines(root)){
    l = l.replace(/[\p{Extended_Pictographic}\u{FE0F}\u{200D}\u{20E3}\u2022\u25AA\u25E6\u2023\u2043\u2713\u2714\u2716\u2717\u2718]/gu, " ")
         .replace(/\s*[→➜➔⟶]\s*/g, ", then ").replace(/\s+[·|]\s+/g, ", ").replace(/^\s*[-–·*]\s+/, "")
         .replace(/^(\d{1,2})(?=[A-Z])/, "$1. ").replace(/([a-z])(\d{1,2})(?=[A-Z])/g, "$1. $2. ")
         .replace(/\s+/g, " ").replace(/^[,\s]+|[,\s]+$/g, "");
    if(!/[A-Za-z0-9]/.test(l)) continue;
    const key = l.toLowerCase().replace(/[^a-z0-9]/g, "");
    if(out.length && out[out.length-1].key === key) continue;   // OBJECTIVE over "Objective": read once
    if(key.length > 12 && out.some(o=>o.key === key)) continue;   // a title shown again lower on the slide
    out.push({l, key});
  }
  return out.map(o=>o.l + (/[.!?:;]$/.test(o.l) ? " " : ". ")).join("").trim();
}
if(typeof Narrator !== "undefined"){
  Narrator.slideText = function(){ const card = document.querySelector("#lessonSlideWrap"); return card ? ftSayText(card) : ""; };
  const __play = Narrator.play;
  Narrator.play = function(){
    if(this.supported && !this.slideText()){ this.stop(true); this.paint(); if(state.audioMode) this.finished(); else toast("This slide has nothing to read aloud."); return; }
    return __play.apply(this, arguments);
  };
  window.ftSayText = ftSayText;
}
})();
